### ISSUE TITLE
Need better definition on what to do on CANCELED_IM.

### ISSUE THREAD

**Issue by joaobrittoneto** [Brazilian-Institute-of-Robotics/drivers-orogen-usbl_evologics#10]
There was a misunderstand on what the CANCELED_IM does.
When there is a pending message and other one is transmitted, the canceled message is not the new one, but the one that is waiting for a delivery_report. The message is transmitted but no delivery report will be received for that one, and the new message is transmitted, waiting for it's delivery report.

**Comment by doudou** [comment]
Shit ... we sat on that for so long. I don't even remember it :(
