### ISSUE TITLE
Task goes to exception when defined as port_driven

### ISSUE THREAD

**Issue by joaobrittoneto** [Brazilian-Institute-of-Robotics/drivers-orogen-usbl_evologics#16]
If the task is set as port_driven, it goes to exception caused by read timeout. 

During debuging, it was checked that the method iodrives_base::hasIO() was returning true, but no left data was checket in the extractPacket buffer. Still needs more investigation on that.

Actually the task execute the updateHook every 'read timeout' period.

**Comment by g-arjones** [comment]
Why port_driven instead of fd_driven? We are getting usbl data from a file descriptor aren't we?

**Comment by joaobrittoneto** [comment]
We need the usbl to send incoming messages (IM or raw data). Now the messages are only sent when the updateHook is called, and it's happening every 'read timeout' period when the usbl is not getting data from the remote device.

It should be both, port_driven and fd_driven, since it's [allowed](http://rock-robotics.org/stable/documentation/orogen/triggering/fd.html).

**Comment by joaobrittoneto** [comment]
The last commit in https://github.com/Brazilian-Institute-of-Robotics/drivers-orogen-usbl_evologics/pull/15, fix it. 
The Task is now port_driven and fd_driven. 

Just a remark, in case there is no data in the file descriptor or in the port to trigger the task, the updateHook is called every `io_read_timeout` period.

**Comment by doudou** [comment]
> The last commit in #15, fix it.

Have you pushed that commit yet ? The last commit in #15 just sets port_driven ....

**Comment by joaobrittoneto** [comment]
https://github.com/Brazilian-Institute-of-Robotics/drivers-orogen-usbl_evologics/pull/15/commits/08f3a88c62cea39215b5367676bc04be8e5553de

**Comment by joaobrittoneto** [comment]
It is fixed by the PR https://github.com/Brazilian-Institute-of-Robotics/drivers-orogen-usbl_evologics/pull/15.
Closing it.
