### ISSUE TITLE
full usbl's buffer

### ISSUE THREAD

**Issue by joaobrittoneto** [Brazilian-Institute-of-Robotics/drivers-orogen-usbl_evologics#26]
The USBL's buffer is getting full when it's not possible to establish an acoustic connection and there is incoming burst data to be transmitted. New incoming burst data is discharged and provided in the output port 'dropped_raw_data'

I'm considering to empty the buffer (when it gets full and there is no acoustic connection).

Pro: Avoid sending old data when a connection is establish, and new data has the possibility to be delivered.
Cons: It would not be possible to track which data is dropped from Usbl's buffer. It requires that only non vital packets uses the burst data.

@g-arjones, @doudou, any comment about that?

**Comment by joaobrittoneto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [USBL buffer full: Investigate](https://trello.com/c/RI0NREQW/107-usbl-buffer-full-investigate)

**Comment by doudou** [comment]
This sounds OK as a quick-fix.

Given the low quality of the link, the best would be to have a static, well-defined, message schedule and degradation policy. State-based, that is one can drop anything between the message sent by the USBL and the message received by the component.

**Comment by joaobrittoneto** [comment]
The quick fix works. 
I'm closing this issue for now
